### ISSUE TITLE
Bug "next" ScamExam

### ISSUE THREAD

**Issue by BZHBlossom** [ScanExam/ScanGrading#2]
Patch le bug "next" qui apparait sur le bouton "next student"

**Comment by Ailkk** [comment]
Bug localisé et compris
Peut être revoir une partie du modèle?
On cherche des solutions possibles à présenter pour le 30/09

**Comment by Ailkk** [comment]
La variable qui cause le problème (defaultGradeIndex) ne renseigne pas uniquement un index d'une note par défaut mais joue également le rôle d'oracle (ou de prédicteur) de la note la plus probable pour une question donnée. Il faut conserver cette notion et trouver comment définir la note par défaut sans retomber sur le bug.
